### ISSUE TITLE
clarify that nginx needs to have the slice module enabled

### ISSUE THREAD

**Issue by Francesco149** [menixator/lancache.nix#2]
hey, thanks for putting this together. nginx doesn't have the slice module by default so it's necessary to add `services.nginx.package = pkgs.nginxMainline.override { withSlice = true; };` to your config for this to work

we could either clarify this in the README or have the module do that

**Comment by menixator** [comment]
added with 45b926d5e05973e0fd9a659c334281809a077a89.
I've also added an example of how I am overriding the dns entries with adguardhome to help folks get started with this.
Cheers.
